# Generated by Django 2.0.4 on 2018-04-10 22:24

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=40, unique=True)),
                ('email', models.EmailField(max_length=256, unique=True)),
                ('user_type', models.SmallIntegerField(choices=[(1, 'manager'), (2, 'client')], default=2)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user_profile',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('from_address', models.CharField(max_length=64, null=True)),
                ('dest_address', models.CharField(max_length=64, null=True)),
                ('deadline', models.DateTimeField(null=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_shipments', to=settings.AUTH_USER_MODEL)),
                ('dest_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_shipments', to='shipments.City')),
            ],
            options={
                'db_table': 'shipment',
            },
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipments.City')),
            ],
            options={
                'db_table': 'street',
            },
        ),
        migrations.AddField(
            model_name='shipment',
            name='dest_street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_shipments', to='shipments.Street'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='from_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_shipments', to='shipments.City'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='from_street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_shipments', to='shipments.Street'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_shipments', to=settings.AUTH_USER_MODEL),
        ),
    ]
